[env:jig1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

upload_port = COM3
monitor_port = COM3
monitor_speed = 115200

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DDEVICE_NAME=\"JIG-01\"
    -DENABLE_RF_CONTROL=1
    -DENABLE_SMO_SIMULATOR=1
    -DENABLE_SERIAL_LOG=1
    -DAP_SSID=\"Auto_Click_JIG01\"
    -DMDNS_NAME=\"gdo-monitor-01\"
    -DBOT_TOKEN=\"8105256477:AAEwQ4J4aAkNWsjPB0Yzrw8X2xJe5J8vEx0\"
    -DCHAT_ID=\"-1003309157934\"
    -DTELEGRAM_COMMAND_SUFFIX=\"1\"

lib_deps =
    bblanchon/ArduinoJson
    tzapu/WiFiManager
      
[env:jig2]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

upload_port = COM3
monitor_port = COM3    
monitor_speed = 115200

build_flags =
    -DDEVICE_NAME=\"JIG-02\"
    -DENABLE_RF_CONTROL=0
    -DENABLE_SMO_SIMULATOR=0
    -DENABLE_SERIAL_LOG=0
    -DAP_SSID=\"Auto_Click_JIG02\"
    -DMDNS_NAME=\"gdo-monitor-02\"
    -DPIN_SMO_UART_TX=7
    -DPIN_SMO_UART_RX=6
    -DBOT_TOKEN=\"8105256477:AAEwQ4J4aAkNWsjPB0Yzrw8X2xJe5J8vEx0\"
    -DCHAT_ID=\"-5498498531\"
    -DTELEGRAM_COMMAND_SUFFIX=\"2\"

lib_deps =
    bblanchon/ArduinoJson
    tzapu/WiFiManager

[env:jig3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

upload_port = COM3
monitor_port = COM3
monitor_speed = 115200

build_flags =
    -DDEVICE_NAME=\"JIG-03\"
    -DENABLE_RF_CONTROL=1
    -DENABLE_SMO_SIMULATOR=0
    -DENABLE_SERIAL_LOG=0
    -DAP_SSID=\"Auto_Click_JIG03\"
    -DMDNS_NAME=\"gdo-monitor-03\"
    -DPIN_SMO_UART_TX=5
    -DPIN_SMO_UART_RX=6
    -DNUM_RELAYS=2
    -DRELAY_1_PIN=0
    -DRELAY_2_PIN=3
    -DRELAY_COUNT_ON_PRESS=0
    -DRELAY_ACTIVE_LOW=0
    -DRELAY_PULSE_MS=500
    -DBOT_TOKEN=\"8105256477:AAEwQ4J4aAkNWsjPB0Yzrw8X2xJe5J8vEx0\"
    -DCHAT_ID=\"-5481519738\"
    -DTELEGRAM_COMMAND_SUFFIX=\"3\"

lib_deps =
    bblanchon/ArduinoJson
    tzapu/WiFiManager
  
