#pragma once

// Device identity
#define DEVICE_NAME "ID100 Battery Monitor"
#define FIRMWARE_VERSION "0.1.0-demo"
#define SCHEMA_VERSION 1

// Local access point
#define AP_SSID "ID100-Battery-Monitor"
#define AP_PASSWORD "12345678"

// ADC channels and sampling
#define ADC_CHANNEL_COUNT 2
#define ADC_SAMPLES 32
#define ADC_SAMPLE_DELAY_US 150
#define ADC_SAMPLE_INTERVAL_MS 1000UL
#define SAMPLES_PER_MINUTE 60
#define MINUTE_AVERAGES_PER_TELEMETRY 10
#define PIN_BATTERY_1 3
#define PIN_BATTERY_2 4

// Battery conversion and thresholds
// Common linear calibration from the averaged GPIO3/GPIO4 sweep.
// battery_mV = adc_mV * slope + offset_mV
#define ADC_CAL_SLOPE 5.98030284811045
#define ADC_CAL_OFFSET_MV -41.9597893112993
#define BATTERY_EMPTY_MV 2400
#define BATTERY_LOW_MV 2500
#define BATTERY_NORMAL_MV 2500
#define BATTERY_FULL_MV 3300
#define BATTERY_DISCONNECTED_MV 500
#define BATTERY_OVER_VOLTAGE_MV (BATTERY_FULL_MV + 150)

// Production EMQX Serverless broker.
#define MQTT_HOST "a5611661.ala.asia-southeast1.emqxsl.com"
#define MQTT_PORT 8883
#define MQTT_USERNAME "esp32c3-001"
#define MQTT_PASSWORD "ZIutdn9Z38QzhC6E"
// Increment this value whenever the built-in MQTT credentials change so an
// already-flashed device refreshes its MQTT settings stored in NVS.
#define MQTT_CONFIG_REVISION 4
#define MQTT_KEEP_ALIVE_SECONDS 30
static constexpr char MQTT_CA_CERT[] = R"PEM(
-----BEGIN CERTIFICATE-----
MIIDjjCCAnagAwIBAgIQAzrx5qcRqaC7KGSxHQn65TANBgkqhkiG9w0BAQsFADBh
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBH
MjAeFw0xMzA4MDExMjAwMDBaFw0zODAxMTUxMjAwMDBaMGExCzAJBgNVBAYTAlVT
MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j
b20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IEcyMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuzfNNNx7a8myaJCtSnX/RrohCgiN9RlUyfuI
2/Ou8jqJkTx65qsGGmvPrC3oXgkkRLpimn7Wo6h+4FR1IAWsULecYxpsMNzaHxmx
1x7e/dfgy5SDN67sH0NO3Xss0r0upS/kqbitOtSZpLYl6ZtrAGCSYP9PIUkY92eQ
q2EGnI/yuum06ZIya7XzV+hdG82MHauVBJVJ8zUtluNJbd134/tJS7SsVQepj5Wz
tCO7TG1F8PapspUwtP1MVYwnSlcUfIKdzXOS0xZKBgyMUNGPHgm+F6HmIcr9g+UQ
vIOlCsRnKPZzFBQ9RnbDhxSJITRNrw9FDKZJobq7nMWxM4MphQIDAQABo0IwQDAP
BgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBhjAdBgNVHQ4EFgQUTiJUIBiV
5uNu5g/6+rkS7QYXjzkwDQYJKoZIhvcNAQELBQADggEBAGBnKJRvDkhj6zHd6mcY
1Yl9PMWLSn/pvtsrF9+wX3N3KjITOYFnQoQj8kVnNeyIv/iPsGEMNKSuIEyExtv4
NeF22d+mQrvHRAiGfzZ0JFrabA0UWTW98kndth/Jsw1HKj2ZL7tcu7XUIOGZX1NG
Fdtom/DzMNU+MeKNhJ7jitralj41E6Vf8PlwUHBHQRFXGU7Aj64GxJUTFy8bJZ91
8rGOmaFvE7FBcf6IKshPECBV1/MUReXgRPTqh5Uykw7+U0b6LJ3/iyK5S9kJRaTe
pLiaWN0bfVKfjllDiIGknibVb63dDcY3fe0Dkhvld1927jyNxF1WW6LZZm6zNTfl
MrY=
-----END CERTIFICATE-----
)PEM";
#define MQTT_RECONNECT_MIN_MS 1000UL
#define MQTT_RECONNECT_MAX_MS 30000UL
#define TELEMETRY_QUEUE_LIMIT 200
#define OFFLINE_HOURLY_COMPACTION_DELAY_MS (3UL * 60UL * 60UL * 1000UL)
#define OFFLINE_COMPACTION_CHECK_MS 60000UL
#define TEN_MINUTE_BATCHES_PER_HOUR 6
